### ISSUE TITLE
Does not work on sublime 3

### ISSUE THREAD

**Issue by musm** [ketan/BeautifyLatex#16]
I had to basically use https://github.com/flipphillips/BeautifyLatex
to get things to work, would be great if we could update this with a PR from 
@flipphillips

**Comment by flipphillips** [comment]
I'm happy to offer one up, I get discouraged when I fix things and then send PRs that are ignored because the project is 'dead' or undermaintained or just dismissed by the author [😊]  so I just didn't bother with this one.



--
flip phillips
http://www.skidmore.edu/~flip
________________________________

**Comment by ketan** [comment]
Sorry, I've been unable to find time to maintain this. I'm happy to transfer ownership of the plugin to @flipphillips if it works for him

**Comment by musm** [comment]
yay I can confirm that things work with @flipphillips 's  fork so I hope we can transition there. Things should be appropriately set up so the plugin can smoothly update with the sublime package manager.

**Comment by flipphillips** [comment]
Ketan- didn’t mean to imply that -you- were not maintaining it… just all of GitHub in general…

I’ll take it over if it will help/simplify things.

— 
Flip Phillips
www.skidmore.edu/~flip

**Comment by ketan** [comment]
> Ketan- didn’t mean to imply that -you- were not maintaining it… just all of GitHub in general…

No offence taken. I'm no longer using this plugin, I'm happy to either make you (@flipphillips) a contributor on this github repo since I'm not sure how to transfer ownership on packagecontrol.io.

Let me know if you're cool with it...

**Comment by tjebb** [comment]
Can't get it to work in ST3 (on osx) either.
On ST2 working correctly.

**Comment by flipphillips** [comment]
Did you try my fork?

--
Flip Phillips
www.skidmore.edu/~flip<http://www.skidmore.edu/~flip>


On May 2, 2017, at 11:43 AM, tjebb <notifications@github.com<mailto:notifications@github.com>> wrote:


Can't get it to work in ST3 (on osx) either.
On ST2 working correctly.

**Comment by flipphillips** [comment]
On Apr 27, 2017, at 1:09 AM, Ketan Padegaonkar <notifications@github.com<mailto:notifications@github.com>> wrote:


Ketan- didn’t mean to imply that -you- were not maintaining it… just all of GitHub in general…

No offence taken. I'm no longer using this plugin, I'm happy to either make you (@flipphillips<https://github.com/flipphillips>) a contributor on this github repo since I'm not sure how to transfer ownership on packagecontrol.io<http://packagecontrol.io>.

Let me know if you're cool with it...

Sure thing. Let's do it. Not sure about package control either. Maybe if we joint-email Wil?

**Comment by cjchristopher** [comment]
I hate to resurrect old issues (but I guess it's still open). However I'm having issues on ST3 on Windows with your fork @flipphillips - beautify commands aren't found at all

Edit: More info - actually, invoking the keyboard shortcut seems to work now (it initially wasn't even after restarting ST3, so possibly just a config problem on my end), so that's great! However sublime still isn't finding the explicit command options

**Comment by musm** [comment]
closing this stale issue
